In [1]:
import numpy as np
import time

Vector creation

In [2]:
a = np.zeros(4)
print(f" np.array(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,))
print(f"np.zeros(4,): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4)
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

 np.array(4): a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,): a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.20269476 0.16134308 0.20514406 0.83534558], a shape = (4,), a data type = float64


In [3]:
a = np.arange(4.)
print(f"np.arange(4.): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4)
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.): a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.47602979 0.40846071 0.18730724 0.82497045], a shape = (4,), a data type = float64


In [ ]:
# quando tem um '.' o tipo torna int
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


In [5]:
#indexing
a = np.arange(10)
print(a)

print(f"a[2].shape: {a[2].shape} a[2] = {a[2]}, Acessing an element returns a scalar")
print(f"a[-1] = {a[-1]}")
try:
    c = a[10]
except Exception as e:
    print("The error messege you will see is: ")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2] = 2, Acessing an element returns a scalar
a[-1] = 9
The error messege you will see is: 
index 10 is out of bounds for axis 0 with size 10


Slicing

In [6]:
a = np.arange(10)
print(f"a                    = {a}")
#start stop step
c = a[2:7:1]
print("a[2:7:1] = ", c)

c = a[2:7:2]
print("a[2:7:2] = ", c)

c = a[3:]
print("a[3:] = ", c)

c = a[:3]
print("a[:3] = ", c)

c = a[:]
print("a[:] = ", c)



a                    = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:] =  [3 4 5 6 7 8 9]
a[:3] =  [0 1 2]
a[:] =  [0 1 2 3 4 5 6 7 8 9]


Single Vector operations

In [8]:
a = np.array([1, 2, 3, 4])
print(f"a :{a}")
b = -a
print(f"b = -a : {b}")
b = np.sum(a)
print(f"b = np.sum(a): {b}")
# mean, media?
b = np.mean(a)
print(f"b = np.mean(a): {b}")
b = a**2
print(f"b = a**2: {b}")
b = np.square(a)
print(f"b = np.square(a): {b}")

a :[1 2 3 4]
b = -a : [-1 -2 -3 -4]
b = np.sum(a): 10
b = np.mean(a): 2.5
b = a**2: [ 1  4  9 16]
b = np.square(a): [ 1  4  9 16]


In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, 3, 4])
print(f"Binary operators work element wise: {a+b}")

Binary operators work element wise: [0 0 6 8]


In [10]:
c = np.array([1,2])
try:
    d = a+c
except Exception as e:
    print("The message you will see is: ")
    print(e)

The message you will see is: 
operands could not be broadcast together with shapes (4,) (2,) 


The need for speed, vector vs for loop

In [12]:
np.random.seed(1)
a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(f"np.dot(a,b) = {c:.4f}")
print(f"Vetorizado versão duração: {10e3 * (toc-tic):.4f}")

def forloop(a, b):
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

tic = time.time()
c = forloop(a, b)
toc = time.time()

print(f"forloop(a, b) = {c:.4f}")
print(f"Forloop versão duração: {10e3 * (toc-tic):.4f}")

del(a)
del(b)

np.dot(a,b) = 2501072.5817
Vetorizado versão duração: 169.5418
forloop(a, b) = 2501072.5817
Forloop versão duração: 28086.7791


In [14]:
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)
print(f"X[1] has shape {X[1].shape}, data type: {X.dtype}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,), data type: int64
w has shape (1,)
c has shape ()


Matrix

In [16]:
a = np.zeros((1,5)) #1x5
print(f"a shape = {a.shape}, a = {a}")

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.04997798]]


In [21]:
a = np.arange(6).reshape(-1,2) #coluna: 2, -1 é qqlr valor para que o total de elemento nao mude
print(f"a.shape: {a.shape}, \na= {a}")

print(f"\na[2,0].shape: {a[2,0].shape}, a[2,0] = {a[2,0]}, type(a[2.0] = {type(a[2,0])} Acessing an element returns a scalarn")
print(f"a[2].shape: {a[2].shape}, a[2] = {a[2]}, type(a[2]) = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape: (), a[2,0] = 4, type(a[2.0] = <class 'numpy.int64'> Acessing an element returns a scalarn
a[2].shape: (2,), a[2] = [4 5], type(a[2]) = <class 'numpy.ndarray'>


In [23]:
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

print("a[0, 2:7:1] = ", a[0, 2:7:1], ", a[0, 2:7:1].shape = ", a[0, 2:7:1].shape, "a 1-D array")
#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] , a[0, 2:7:1].shape =  (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
